name: AWS Deploy
on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.AWS_GITHUB_WORKFLOW_ROLE}}
          aws-region: ap-northeast-1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          npm install serverless -g
          npm ci
      - name: serverless deploy
        run: |
          sls deploy
        env:
          DYNAMODB_TABLE: ${{secrets.DYNAMODB_TABLE}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
          S3_MESSAGE_OBJ_KEY: ${{secrets.S3_MESSAGE_OBJ_KEY}}
          LINE_ACCESS_TOKEN: ${{secrets.LINE_ACCESS_TOKEN}}
          LINE_CHANNEL_SECRET: ${{secrets.LINE_CHANNEL_SECRET}}
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
